# Site Settings
title: TermoBlog
email: dolceymendozajr@gmail.com
description: Blog de termodin√°mica para ExpoFisica.
baseurl: "/ExpoFisica" # the subpath of your site, e.g. /blog
url: "https://dolceymendozajr.github.io" # the base hostname & protocol for your site
google_analytics: "UA-XXXXXXXX-X"

# User Settings
username: Dolcey Mendoza Anaya
user_description: Programador.
disqus_username: dolceymendoza

# Social Media
# Remove the item if you don't need it
github_username: dolceymendozajr
facebook_username: dolceymendozajr
twitter_username: dolceymendozajr
instagram_username: dolceymendozajr

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
gems:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
